language: objective-c
osx_image: xcode7.3
install:
  - cd Example/BFTaskPromiseExample
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - pod install
script:
  - bundle exec rake test coverage:coveralls

branches:
  only: 
    - master
    - travis-test
