language: objective-c
osx_image: xcode9.4
install:
  - cd Example/BFTaskPromiseExample
  - bundle install --path=vendor/bundle --binstubs=vendor/bin
  - pod install
script:
  - bundle exec rake test coverage:coveralls
