require 'xcjobs'

XCJobs::Test.new('test') do |t|
  t.build_dir = 'build'
  t.workspace = 'BFTaskPromiseExample'
  t.scheme = 'BFTaskPromiseExample'
  t.configuration = 'Release'
  t.add_destination('platform=iOS Simulator,name=iPad Air,OS=8.1')
  t.formatter = 'xcpretty -c'
  t.coverage = true
end

class MyCoveralls < XCJobs::Coverage::Coveralls
      def upload(json_file)
        curl_options = ['curl',  '-F', "json_file=@#{json_file}", 'https://coveralls.io/api/v1/jobs']
        puts curl_options.join(' ')
        Open3.popen2e(*curl_options) do |stdin, stdout_err, wait_thr|
          output = ''
          while line = stdout_err.gets
            puts line
            output << line
          end
      
          status = wait_thr.value
          if !status.success?
            fail "upload failed (exited with status: #{status.exitstatus})"
          end
        end
      end
  
end

MyCoveralls.new() do |t|
  puts "ENV['TRAVIS_JOB_ID']: #{ENV['TRAVIS_JOB_ID']}"
  t.add_extension('.m')
  t.add_exclude('Example/BFTaskPromiseExample/BFTaskPromiseExampleTests')
end
